language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench run --report=default --group=trait


after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com

sudo: false
