language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench

after_script:
  - vendor/bin/coveralls

notifications:
  email: harmenstoppels@gmail.com

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
