language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer selfupdate
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpbench

after_script:
  - vendor/bin/coveralls

sudo: false
